# Generated by Django 3.2.7 on 2021-10-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_archive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
